# Generated by Django 4.2.3 on 2023-07-23 18:45

import RentalApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RentalApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "social_security_number",
                    RentalApp.models.SocialSecurityNumberField(max_length=11),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("apartment_location", models.CharField(max_length=200)),
                ("date_and_time", models.DateTimeField()),
                ("date_of_birth", models.DateField(null=True)),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("driver_license_number", models.CharField(max_length=100)),
                ("present_home_address", models.CharField(max_length=200)),
                ("length_of_time_at_address", models.CharField(max_length=100)),
                ("landlord_phone", models.CharField(max_length=20)),
                ("reason_for_leaving", models.CharField(max_length=200)),
                ("amount_of_rent", models.CharField(max_length=5)),
                ("is_rent_up_to_date", models.BooleanField()),
                ("number_of_occupants", models.IntegerField()),
                ("number_of_pets", models.IntegerField()),
                ("number_of_vehicles", models.IntegerField()),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("employed", "Employed"),
                            ("unemployed", "Unemployed"),
                            ("student", "Student"),
                            ("retired", "Retired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_employer", models.CharField(max_length=200)),
                ("occupation", models.CharField(max_length=200)),
                ("supervisor", models.CharField(max_length=100)),
                ("hours_per_week", models.CharField(max_length=100)),
                ("employer_phone", models.CharField(max_length=20)),
                ("years_employed", models.CharField(max_length=100)),
                ("employment_address", models.CharField(max_length=200)),
                (
                    "current_income",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("bi-weekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_income_amount", models.CharField(max_length=100)),
                ("income_source", models.CharField(max_length=100)),
                ("has_proof_of_income", models.BooleanField()),
                ("car_loan_lien_holder", models.CharField(max_length=200)),
                ("car_loan_balance", models.IntegerField()),
                ("car_loan_monthly_payment", models.IntegerField()),
                ("car_loan_creditor_phone", models.CharField(max_length=20)),
                ("credit_card_company", models.CharField(max_length=200)),
                ("credit_card_balance_owed", models.IntegerField()),
                ("credit_card_monthly_payment", models.IntegerField()),
                ("creditor_phone_number", models.CharField(max_length=20)),
                (
                    "child_support_creditor_owed",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "child_support_balance",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "child_support_monthly_payment",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "child_support_creditor_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("bank_account_name", models.CharField(max_length=200)),
                ("bank_account_balance", models.IntegerField()),
                ("bank_account_monthly_payment", models.IntegerField()),
                ("account_number", models.CharField(max_length=100)),
                ("emergency_contact", models.CharField(max_length=100)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                ("emergency_contact_relationship", models.CharField(max_length=100)),
                ("emergency_contact_address", models.CharField(max_length=200)),
                ("personal_reference_name", models.CharField(max_length=100)),
                ("personal_reference_contact_phone", models.CharField(max_length=20)),
                (
                    "personal_reference_contact_relationship",
                    models.CharField(max_length=100),
                ),
                (
                    "personal_reference_contact_address",
                    models.CharField(max_length=200),
                ),
                ("has_been_sued", models.BooleanField()),
                ("has_been_bankrupt", models.BooleanField()),
                ("guilty_of_felony", models.BooleanField()),
                ("has_broken_lease", models.BooleanField()),
                ("has_been_locked_out_by_sheriff", models.BooleanField()),
                ("has_been_brought_to_court", models.BooleanField()),
                ("has_moved_owing_rent_or_damaged", models.BooleanField()),
                ("is_move_in_amount_available", models.BooleanField()),
                ("signature", models.CharField(max_length=200)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_year", models.IntegerField()),
                ("vehicle_make", models.CharField(max_length=100)),
                ("vehicle_model", models.CharField(max_length=100)),
                ("vehicle_plate_number", models.CharField(max_length=20)),
                ("vehicle_plate_state", models.CharField(max_length=20)),
                (
                    "rental_application",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="RentalApp.rentalapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "pet_type",
                    models.CharField(
                        choices=[
                            ("small_dog", "Small Dog (under 10 LBS)"),
                            ("medium_dog", "Medium Dog (Over 10 Under 35 LBS)"),
                            ("large_dog", "Large Dog (Over 35 LBS)"),
                            ("pit_bull", "Pit Bull"),
                            ("cat", "Cat"),
                            ("bird", "Bird"),
                            ("fish", "Fish"),
                            ("rabbit", "Rabbit"),
                            ("hamster", "Hamster"),
                            ("guinea_pig", "Guinea Pig"),
                            ("turtle", "Turtle"),
                            ("snake", "Snake"),
                            ("lizard", "Lizard"),
                            ("horse", "Horse"),
                            ("goat", "Goat"),
                            ("reptile", "Reptile"),
                            ("duck", "Duck"),
                            ("amphibian", "Amphibian"),
                            ("insect", "Insect"),
                            ("rodent", "Rodent"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "indoor_outdoor",
                    models.CharField(
                        choices=[
                            ("Indoor", "Indoor"),
                            ("Outdoor", "Outdoor"),
                            ("Indoor_Outdoor", "Indoor/Outdoor"),
                        ],
                        max_length=14,
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "rental_application",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="RentalApp.rentalapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Occupant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("parent", "Parent"),
                            ("sibling", "Sibling"),
                            ("self", "Self"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("employed", "Employed"),
                            ("unemployed", "Unemployed"),
                            ("student", "Student"),
                            ("retired", "Retired"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("under18", "Under 18"),
                            ("18-25", "18 to 25"),
                            ("26-35", "26 to 35"),
                            ("36-45", "36 to 45"),
                            ("46-55", "46 to 55"),
                            ("56-65", "56 to 65"),
                            ("over65", "Over 65"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "rental_application",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupants",
                        to="RentalApp.rentalapplication",
                    ),
                ),
            ],
        ),
    ]
