# Generated by Django 4.2.3 on 2023-07-19 18:37

import RentalApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Occupant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("parent", "Parent"),
                            ("sibling", "Sibling"),
                            ("self", "Self"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("employed", "Employed"),
                            ("unemployed", "Unemployed"),
                            ("student", "Student"),
                            ("retired", "Retired"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("under18", "Under 18"),
                            ("18-25", "18 to 25"),
                            ("26-35", "26 to 35"),
                            ("36-45", "36 to 45"),
                            ("46-55", "46 to 55"),
                            ("56-65", "56 to 65"),
                            ("over65", "Over 65"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "pet_type",
                    models.CharField(
                        choices=[
                            ("small_dog", "Small Dog (under 10 LBS)"),
                            ("medium_dog", "Medium Dog (Over 10 Under 35 LBS)"),
                            ("large_dog", "Large Dog (Over 35 LBS)"),
                            ("pit_bull", "Pit Bull"),
                            ("cat", "Cat"),
                            ("bird", "Bird"),
                            ("fish", "Fish"),
                            ("rabbit", "Rabbit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "indoor_outdoor",
                    models.CharField(
                        choices=[
                            ("indoor", "Indoor"),
                            ("outdoor", "Outdoor"),
                            ("indoor_outdoor", "Indoor/Outdoor"),
                        ],
                        max_length=14,
                    ),
                ),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_year", models.CharField(max_length=4)),
                ("vehicle_make", models.CharField(max_length=100)),
                ("vehicle_model", models.CharField(max_length=100)),
                ("vehicle_plate_number", models.CharField(max_length=20)),
                ("vehicle_plate_state", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="RentalApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "social_security_number",
                    RentalApp.models.SocialSecurityNumberField(max_length=11),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("apartment_location", models.CharField(max_length=200)),
                ("date_and_time", models.DateTimeField()),
                ("date_of_birth", models.DateField()),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("driver_license_number", models.CharField(max_length=100)),
                ("present_home_address", models.CharField(max_length=200)),
                ("length_of_time_at_address", models.CharField(max_length=100)),
                ("landlord_phone", models.CharField(max_length=20)),
                ("reason_for_leaving", models.CharField(max_length=200)),
                ("amount_of_rent", models.CharField(max_length=5)),
                (
                    "is_rent_up_to_date",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                ("number_of_occupants", models.IntegerField()),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("employed", "Employed"),
                            ("unemployed", "Unemployed"),
                            ("student", "Student"),
                            ("retired", "Retired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_employer", models.CharField(max_length=200)),
                ("occupation", models.CharField(max_length=200)),
                ("supervisor", models.CharField(max_length=100)),
                ("hours_per_week", models.CharField(max_length=100)),
                ("employer_phone", models.CharField(max_length=20)),
                ("years_employed", models.CharField(max_length=100)),
                ("employment_address", models.CharField(max_length=200)),
                (
                    "current_income",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("bi-weekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_income_amount", models.CharField(max_length=100)),
                ("income_source", models.CharField(max_length=100)),
                (
                    "has_proof_of_income",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                ("car_loan_lien_holder", models.CharField(max_length=200)),
                ("car_loan_balance", models.CharField(max_length=100)),
                ("car_loan_monthly_payment", models.CharField(max_length=100)),
                ("car_loan_creditor_phone", models.CharField(max_length=20)),
                ("credit_card_company", models.CharField(max_length=200)),
                ("credit_card_balance_owed", models.CharField(max_length=100)),
                ("credit_card_monthly_payment", models.CharField(max_length=100)),
                ("creditor_phone_number", models.CharField(max_length=20)),
                ("child_support_creditor_owed", models.CharField(max_length=200)),
                ("child_support_balance", models.CharField(max_length=100)),
                ("child_support_monthly_payment", models.CharField(max_length=100)),
                ("child_support_creditor_phone", models.CharField(max_length=20)),
                ("bank_account_name", models.CharField(max_length=200)),
                ("bank_account_balance", models.CharField(max_length=100)),
                ("bank_account_monthly_payment", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=100)),
                ("emergency_contact", models.CharField(max_length=100)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                ("emergency_contact_relationship", models.CharField(max_length=100)),
                ("emergency_contact_address", models.CharField(max_length=200)),
                ("personal_reference_name", models.CharField(max_length=100)),
                ("personal_reference_contact_phone", models.CharField(max_length=20)),
                (
                    "personal_reference_contact_relationship",
                    models.CharField(max_length=100),
                ),
                (
                    "personal_reference_contact_address",
                    models.CharField(max_length=200),
                ),
                (
                    "has_been_sued",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "has_been_bankrupt",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "has_guilty_of_felony",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "has_broken_lease",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "has_been_locked_out_by_sheriff",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "has_been_brought_to_court",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "has_moved_owing_rent_or_damaged",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "is_move_in_amount_available",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                ("photo_id", models.ImageField(upload_to="rental_photos")),
                ("signature", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("pets", models.ManyToManyField(blank=True, to="RentalApp.pet")),
                (
                    "vehicles",
                    models.ManyToManyField(blank=True, to="RentalApp.vehicle"),
                ),
            ],
        ),
    ]
