# Generated by Django 4.2.3 on 2023-07-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RentalApp", "0002_alter_rentalapplication_child_support_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalapplication",
            name="child_support_balance",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="rentalapplication",
            name="child_support_creditor_owed",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="rentalapplication",
            name="child_support_creditor_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="rentalapplication",
            name="child_support_monthly_payment",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="rentalapplication",
            name="has_been_bankrupt",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rentalapplication",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
