# Generated by Django 4.2.3 on 2023-07-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RentalApp", "0003_alter_rentalapplication_child_support_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalapplication",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
