# Generated by Django 4.2.3 on 2023-07-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RentalApp", "0004_alter_rentalapplication_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalapplication",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
