# Generated by Django 4.2.3 on 2023-07-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RentalApp", "0005_alter_rentalapplication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalapplication",
            name="pets",
            field=models.ManyToManyField(to="RentalApp.pet"),
        ),
    ]
